$(document).ready(function() {
	$('.menu_popup a').mouseenter(function(){
		var id_pop = $(this).parent().attr('id'); // id пункта меню
		var content = null;
		switch (id_pop) {
			case '0': content = "<table><tr><td id='one' valign='top'><span>Компания</span><ul><li><a href='/about/question/'>Вопросы и ответы</a></li><li><a href='/about/reviews/'>Отзывы</a></li><li><a href='/about/article/'>Статьи</a></li><li><a href='/about/contacts/'>Контакты</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '1': content = "<table><tr><td id='one' valign='top'><span>Строительные блоки</span><ul><li><a href='/catalog/blocks_of_aerated/?SECTION_ID=13&PARENT_ID=12'>Блоки газосиликатные, цена от 2750 руб /м3</a></li><li><a href='/catalog/u_blocks/?SECTION_ID=36'>U-Блоки</a></li><li><a href='/catalog/cost_blocks/?SECTION_ID=99'>Инструмент для газобетона</a></li><li><a href='/catalog/blocks_and_jumpers/?SECTION_ID=14&PARENT_ID=12'>Блоки и перемычки полистиролбетонные</a></li><li><a href='/catalog/claydite_concrete_blocks/?SECTION_ID=15&PARENT_ID=12'>Блоки керамзитобетонные</a></li><li><a href='/catalog/peskotsementnye_blocks/?SECTION_ID=35'>Пескоцементные блоки</a></li><li><a href='/catalog/the_house_of_aerated/?SECTION_ID=16&PARENT_ID=12'>Дом из газобетонных блоков</a></li><li><a href='/'>Пеноблоки цена от 2600 р/м3</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '2': content = "<table><tr><td id='one' valign='top'><span>Кирпич</span><ul><li><a href='/catalog/brick_construction_private/?SECTION_ID=19&PARENT_ID=6'>Кирпич строительный полнотелый</a></li><li><a href='/catalog/brick_slot_effective/?SECTION_ID=20&PARENT_ID=6'>Щелевой кирпич (эффективный)</a></li><li><a href='/catalog/brick_front/?SECTION_ID=18&PARENT_ID=6'>Кирпич облицовочный</a></li><li><a href='/catalog/cost_blocks/?SECTION_ID=99'>Кирпич Лицевой TERCA</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '3': content = "<table><tr><td id='one' valign='top'><span>Железобетонные изделия</span><ul><li><a href='/catalog/piles_zabivnye/?SECTION_ID=28&PARENT_ID=25'>Сваи забивные</a></li><li><a href='/catalog/foundation_blocks_/?SECTION_ID=29&PARENT_ID=25'>Фундаментные блоки и фундаментные подушки (ФЛ)</a></li><li><a href='/catalog/jumper/?SECTION_ID=30&PARENT_ID=25'>Перемычки</a></li><li><a href='/catalog/floor_slabs/?SECTION_ID=31&PARENT_ID=25'>Плиты перекрытия</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '4': content = "<table><tr><td id='one' valign='top'><span>Перегородки</span><ul><li><a href='/catalog/partition_wall_claydite_concrete/?SECTION_ID=23&PARENT_ID=9'>Пазогребневые плиты</a></li><li><a href='/catalog/aerated_concrete_slab/?SECTION_ID=22&PARENT_ID=9'>Плиты газобетонные</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '5': content = "<table><tr><td id='one' valign='top'><span>Утеплители</span><ul><li><a href='/catalog/mineral_wool_plate/?SECTION_ID=32&PARENT_ID=26'>Минплита</a></li><li><a href='/catalog/polystyrene_icb_with/?SECTION_ID=33&PARENT_ID=26'>Пенополистирол (ПСБ-С)</a></li><li><a href='/catalog/leca/?SECTION_ID=34&PARENT_ID=26'>Керамзит</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '6': content = "<table><tr><td id='one' valign='top'><span>Сухие смеси</span><ul><li><a href='/catalog/dry_mixes/?SECTION_ID=17'>Клей для газобетона</a></li></ul><span>Производители</span><ul><li><a href='/main/company/bbk/'>ВВКЗ</a></li><li><a href='/main/company/grask/'>Калужский кирпичный завод</a></li><li><a href='/main/company/lkz/'>Тверской КСМ</a></li></ul></td><td id='two' valign='top'><span>Статьи</span><ul><li><a href='/'>Кирпич облицовочный: разумная цена за достойное качество</a></li><li><a href='/'>Внутренние стены из щелевого кирпича</a></li><li><a href='/'>Облицовочный кирпич: виды и преимущества использования</a></li><li><a href='/'>Облегченные стены из кирпича щелевого</a></li></ul><div id='rev_q'><a href='/about/question/'>Вопросы и ответы  >></a><a href='/reviews/'>Все отзывы  >></a></div></td></tr></table>"; break;
			case '7': return false; break;
		}
		var submenu = $('.popup_active, img#'+id_pop+'');
		$('img.popup_active_img').hide();
		$('div#popup').empty();

		$("div#popup").append(content);
		$('li#'+id_pop).append($("div#popup"));
				
		submenu.fadeIn(700);

		$('.popup_active').mouseleave(function(){
			$(this).fadeOut(400);
			$('img.popup_active_img').fadeOut(400);
		});
			
	});
});